version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: HariKrish123
      POSTGRES_DB: pahrikyns
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    container_name: pahrikyns-backend
    build:
      context: ./pahrikyns-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./pahrikyns-backend/.env
    depends_on:
      - db
    command: sh -c "npx prisma generate && node server.js"  
    restart: unless-stopped

  frontend:
    container_name: pahrikyns-frontend
    build:
      context: ./pahrikyns-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file: ./pahrikyns-frontend/.env   # optional, if frontend needs env
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
